// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhaTro.Data;

#nullable disable

namespace NhaTro.Migrations
{
    [DbContext(typeof(NhaTroDbContext))]
    [Migration("20260417150420_FixColumnsFinal")]
    partial class FixColumnsFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NhaTro.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<DateOnly?>("ActualEndDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_end_date");

                    b.Property<decimal>("ActualRoomPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("actual_room_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DepositAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("deposit_amount");

                    b.Property<DateOnly?>("ExpectedEndDate")
                        .HasColumnType("date")
                        .HasColumnName("expected_end_date");

                    b.Property<int>("OccupantCount")
                        .HasColumnType("int")
                        .HasColumnName("occupant_count");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("ContractId");

                    b.HasIndex("TenantId");

                    b.HasIndex("RoomId", "Status")
                        .HasDatabaseName("IX_contracts_room_id_status");

                    b.ToTable("contracts", null, t =>
                        {
                            t.HasCheckConstraint("CK_contracts_actual_room_price", "actual_room_price > 0");

                            t.HasCheckConstraint("CK_contracts_deposit_amount", "deposit_amount >= 0");

                            t.HasCheckConstraint("CK_contracts_occupant_count", "occupant_count > 0");

                            t.HasCheckConstraint("CK_contracts_status", "status IN ('active', 'ended')");
                        });
                });

            modelBuilder.Entity("NhaTro.Models.DepositSettlement", b =>
                {
                    b.Property<int>("DepositSettlementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("deposit_settlement_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepositSettlementId"));

                    b.Property<int?>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    b.Property<string>("ContractSnapshotJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contract_snapshot_json");

                    b.Property<decimal>("DeductedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("deducted_amount");

                    b.Property<decimal>("DepositAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("deposit_amount");

                    b.Property<decimal>("FinalInvoiceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("final_invoice_amount");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<decimal>("RefundedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("refunded_amount");

                    b.Property<DateTime>("SettledAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("settled_at");

                    b.HasKey("DepositSettlementId");

                    b.HasIndex("ContractId")
                        .IsUnique()
                        .HasFilter("[contract_id] IS NOT NULL");

                    b.ToTable("deposit_settlements", null, t =>
                        {
                            t.HasCheckConstraint("CK_deposit_settlements_deducted_amount", "deducted_amount >= 0");

                            t.HasCheckConstraint("CK_deposit_settlements_refunded_amount", "refunded_amount >= 0");
                        });
                });

            modelBuilder.Entity("NhaTro.Models.EmailNotification", b =>
                {
                    b.Property<int>("EmailNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("email_notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailNotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("NotificationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("notification_type");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("subject");

                    b.Property<string>("TargetEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("target_email");

                    b.HasKey("EmailNotificationId");

                    b.ToTable("email_notifications", (string)null);
                });

            modelBuilder.Entity("NhaTro.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("invoice_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateOnly?>("BillingMonth")
                        .HasColumnType("date")
                        .HasColumnName("billing_month");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    b.Property<string>("ContractSnapshotJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contract_snapshot_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DebtAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("debt_amount");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("ElectricityFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("electricity_fee");

                    b.Property<decimal>("ExtraFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("extra_fee");

                    b.Property<string>("ExtraFeeNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("extra_fee_note");

                    b.Property<DateOnly?>("FromDate")
                        .HasColumnType("date")
                        .HasColumnName("from_date");

                    b.Property<string>("InvoiceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("invoice_type");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<decimal?>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paid_amount");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("paid_at");

                    b.Property<string>("PaymentCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_code");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_reference");

                    b.Property<int?>("ReplacedByInvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("replaced_by_invoice_id");

                    b.Property<decimal>("RoomFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("room_fee");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("ToDate")
                        .HasColumnType("date")
                        .HasColumnName("to_date");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<decimal>("TrashFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("trash_fee");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("WaterFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("water_fee");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ContractId");

                    b.HasIndex("PaymentCode")
                        .IsUnique()
                        .HasFilter("[payment_code] IS NOT NULL");

                    b.HasIndex("ReplacedByInvoiceId");

                    b.HasIndex("RoomId", "BillingMonth", "InvoiceType")
                        .HasDatabaseName("IX_invoices_room_month_type");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_invoices_invoice_type", "invoice_type IN ('monthly', 'final')");

                            t.HasCheckConstraint("CK_invoices_status", "status IN ('unpaid', 'paid')");
                        });
                });

            modelBuilder.Entity("NhaTro.Models.MeterReading", b =>
                {
                    b.Property<int>("MeterReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("meter_reading_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeterReadingId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("BillingMonth")
                        .HasColumnType("date")
                        .HasColumnName("billing_month");

                    b.Property<int>("ConsumedUnits")
                        .HasColumnType("int")
                        .HasColumnName("consumed_units");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    b.Property<string>("ContractSnapshotJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contract_snapshot_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentReading")
                        .HasColumnType("int")
                        .HasColumnName("current_reading");

                    b.Property<int>("PreviousReading")
                        .HasColumnType("int")
                        .HasColumnName("previous_reading");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("MeterReadingId");

                    b.HasIndex("ContractId");

                    b.HasIndex("RoomId", "BillingMonth")
                        .IsUnique();

                    b.ToTable("meter_readings", null, t =>
                        {
                            t.HasCheckConstraint("CK_meter_readings_consumed_units", "consumed_units >= 0");

                            t.HasCheckConstraint("CK_meter_readings_current_vs_previous", "current_reading >= previous_reading");
                        });
                });

            modelBuilder.Entity("NhaTro.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentTransactionId"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("account_number");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("MatchedInvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("matched_invoice_id");

                    b.Property<string>("PaymentCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_code");

                    b.Property<string>("ProcessStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("process_status");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderTransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("provider_transaction_id");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("raw_payload_json");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reference_code");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("transaction_date");

                    b.Property<decimal?>("TransferAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("transfer_amount");

                    b.Property<string>("TransferType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("transfer_type");

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("MatchedInvoiceId");

                    b.HasIndex("ProviderTransactionId")
                        .IsUnique();

                    b.ToTable("payment_transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_payment_transactions_process_status", "process_status IN ('received', 'matched', 'paid', 'ignored', 'failed')");
                        });
                });

            modelBuilder.Entity("NhaTro.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("ListedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("listed_price");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("room_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("RoomId");

                    b.HasIndex("RoomCode")
                        .IsUnique();

                    b.ToTable("rooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_rooms_status", "status IN ('vacant', 'occupied')");
                        });
                });

            modelBuilder.Entity("NhaTro.Models.SystemSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("setting_key");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("setting_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("SettingKey");

                    b.ToTable("system_settings", (string)null);
                });

            modelBuilder.Entity("NhaTro.Models.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<string>("CCCD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cccd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("NhaTro.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("ItemName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("item_name");

                    b.Property<int?>("RelatedInvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("related_invoice_id");

                    b.Property<int?>("RelatedRoomId")
                        .HasColumnType("int")
                        .HasColumnName("related_room_id");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionDirection")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("transaction_direction");

                    b.HasKey("TransactionId");

                    b.HasIndex("RelatedInvoiceId");

                    b.HasIndex("RelatedRoomId");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_transactions_amount", "amount > 0");

                            t.HasCheckConstraint("CK_transactions_category", "category IN ('operating', 'other')");

                            t.HasCheckConstraint("CK_transactions_direction", "transaction_direction IN ('income', 'expense')");
                        });
                });

            modelBuilder.Entity("NhaTro.Models.Contract", b =>
                {
                    b.HasOne("NhaTro.Models.Room", "Room")
                        .WithMany("Contracts")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhaTro.Models.Tenant", "Tenant")
                        .WithMany("Contracts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NhaTro.Models.DepositSettlement", b =>
                {
                    b.HasOne("NhaTro.Models.Contract", "Contract")
                        .WithOne("DepositSettlement")
                        .HasForeignKey("NhaTro.Models.DepositSettlement", "ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("NhaTro.Models.Invoice", b =>
                {
                    b.HasOne("NhaTro.Models.Contract", "Contract")
                        .WithMany("Invoices")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NhaTro.Models.Invoice", "ReplacedByInvoice")
                        .WithMany("ReplacingInvoices")
                        .HasForeignKey("ReplacedByInvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NhaTro.Models.Room", "Room")
                        .WithMany("Invoices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("ReplacedByInvoice");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("NhaTro.Models.MeterReading", b =>
                {
                    b.HasOne("NhaTro.Models.Contract", "Contract")
                        .WithMany("MeterReadings")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NhaTro.Models.Room", "Room")
                        .WithMany("MeterReadings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("NhaTro.Models.PaymentTransaction", b =>
                {
                    b.HasOne("NhaTro.Models.Invoice", "MatchedInvoice")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("MatchedInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MatchedInvoice");
                });

            modelBuilder.Entity("NhaTro.Models.Transaction", b =>
                {
                    b.HasOne("NhaTro.Models.Invoice", "RelatedInvoice")
                        .WithMany("Transactions")
                        .HasForeignKey("RelatedInvoiceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NhaTro.Models.Room", "RelatedRoom")
                        .WithMany("Transactions")
                        .HasForeignKey("RelatedRoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RelatedInvoice");

                    b.Navigation("RelatedRoom");
                });

            modelBuilder.Entity("NhaTro.Models.Contract", b =>
                {
                    b.Navigation("DepositSettlement");

                    b.Navigation("Invoices");

                    b.Navigation("MeterReadings");
                });

            modelBuilder.Entity("NhaTro.Models.Invoice", b =>
                {
                    b.Navigation("PaymentTransactions");

                    b.Navigation("ReplacingInvoices");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("NhaTro.Models.Room", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Invoices");

                    b.Navigation("MeterReadings");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("NhaTro.Models.Tenant", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
