name: .NET CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore NhaTro.sln

      - name: Build
        run: dotnet build NhaTro.sln --no-restore --configuration Release

      - name: Publish
        run: dotnet publish NhaTro.csproj --no-build --configuration Release -o ./publish

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: nhatro-publish
          path: ./publish